apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: [[ .Namespace ]]
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - "[[ .Env.ServiceHost ]]"
  rules:
  - host: "[[ .Env.ServiceHost ]]"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
