apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: [[ .Namespace ]]
  labels:
    app: {{ .Values.app.name }}
    environment: [[ .Environment ]]
    monitoring: {{ .Values.app.name }}-sm-[[ .Environment ]]
    version: {{ .Values.image.tag }}
    AccountableTeam: My
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app.name }}

