apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: cmp
  name: {{ .Values.app.name }}-sm-[[ .Environment ]]
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      monitoring: {{ .Values.app.name }}-sm-[[ .Environment ]]
